In [1]:
# Bài 1
import torch

a = torch.tensor(
    [[1,2,3],
    [4,5,6]],
    dtype = torch.int32)

print(a)
print('Kích thước: ', a.shape)
print('Số chiều: ', a.ndim)
print('Kiểu dữ liệu: ', a.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
Kích thước:  torch.Size([2, 3])
Số chiều:  2
Kiểu dữ liệu:  torch.int32


In [12]:
# Bài 2
import torch

a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)


print(a)
print(b)
print(c)
print(d)
print(e)

# Yêu cầu 2
f = torch.ones(5, 5) * 10
print(f)

tensor([[0.8131, 0.6171, 0.3160, 0.6278],
        [0.3992, 0.2869, 0.4820, 0.3805],
        [0.6653, 0.9463, 0.0372, 0.7275]])
tensor([[-1.9773, -1.1412, -0.9037,  2.1061],
        [ 1.3115, -0.4667,  1.1578, -0.7738],
        [-0.1717,  0.3171, -0.2461,  0.4604]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]])


In [3]:
# Bài 3
import torch

a = torch.zeros(2, 3, 4)

print('Tensor: ')
print(a)
print('Shape: ', a.shape)
print('Size: ', a.size())
print('Number of demensions: ', a.ndim)
print('Data type: ', a.dtype)

Tensor: 
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape:  torch.Size([2, 3, 4])
Size:  torch.Size([2, 3, 4])
Number of demensions:  3
Data type:  torch.float32


In [4]:
# Bài 4
import torch

a = torch.randn(3, 4, 5)

print("Original tensor:")
print(a)

print("\nTensor a[1]:")
print(a[1])

print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

# Yêu cầu 1
print('\nShape của a[1]: ', a[1].shape)
print('Shape của a[1:, 2:4]: ', a[1:, 2:4].shape)

# Yêu cầu 2
two_last_elements = a[:, :, -2:]
print('\nHai phần tử cuối cùng trên chiều thứ 3: ', two_last_elements)

Original tensor:
tensor([[[-1.7714, -0.2383, -0.2525, -0.4499, -0.5160],
         [ 0.0918, -0.7397,  0.6525,  0.7601, -0.2419],
         [ 1.0256, -0.7363, -0.6953, -0.7863, -0.7951],
         [-1.2296, -0.0975,  1.9090,  0.2379,  0.0969]],

        [[ 0.2119, -1.1883, -1.1560,  1.2388, -1.2643],
         [-0.8529,  1.2119, -1.2189, -1.2108, -1.3333],
         [-1.0891,  0.4937,  2.3498,  1.2867,  1.4260],
         [-1.5272,  1.0600,  0.8874,  0.6752, -0.5109]],

        [[ 0.0643,  1.9002,  0.5141, -0.0224, -0.4026],
         [-0.6178,  0.1390, -0.2069,  1.5061,  2.2540],
         [ 2.2046,  0.3882,  0.7581,  1.0256, -0.0717],
         [-1.5554, -1.5874,  1.8864,  0.9603,  0.3934]]])

Tensor a[1]:
tensor([[ 0.2119, -1.1883, -1.1560,  1.2388, -1.2643],
        [-0.8529,  1.2119, -1.2189, -1.2108, -1.3333],
        [-1.0891,  0.4937,  2.3498,  1.2867,  1.4260],
        [-1.5272,  1.0600,  0.8874,  0.6752, -0.5109]])

Tensor a[1:, 2:4]:
tensor([[[-1.0891,  0.4937,  2.3498,  1.2867,  1.4

In [5]:
# Bài 5
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)

print("\nFlatten:")
print(a.ravel())

print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

# Yêu cầu 1
print('Kiểm tra số phần tử:')
print("Số phần tử ban đầu (3x4): ", a.numel())
print("Số phần tử sau ravel(): ", a.ravel().numel())
print("Số phần tử sau reshape(3, 2, 2): ", a.reshape(3, 2, 2).numel())

# Yêu cầu 2
a_2x6 = a.reshape(2, 6)
print("\nReshape thành (2, 6)")
print(a_2x6)
print("Shape mới: ", a_2x6.shape)
print("Số phần tử sau reshape(2, 6) :", a_2x6.numel())

Original:
tensor([[-1.2162, -0.7479, -0.6522,  1.2372],
        [-1.9036,  1.0821, -0.5588,  0.7608],
        [ 0.3833,  1.2097,  1.8297,  0.1822]])

Flatten:
tensor([-1.2162, -0.7479, -0.6522,  1.2372, -1.9036,  1.0821, -0.5588,  0.7608,
         0.3833,  1.2097,  1.8297,  0.1822])

Reshape to 3 x 2 x 2:
tensor([[[-1.2162, -0.7479],
         [-0.6522,  1.2372]],

        [[-1.9036,  1.0821],
         [-0.5588,  0.7608]],

        [[ 0.3833,  1.2097],
         [ 1.8297,  0.1822]]])
Kiểm tra số phần tử:
Số phần tử ban đầu (3x4):  12
Số phần tử sau ravel():  12
Số phần tử sau reshape(3, 2, 2):  12

Reshape thành (2, 6)
tensor([[-1.2162, -0.7479, -0.6522,  1.2372, -1.9036,  1.0821],
        [-0.5588,  0.7608,  0.3833,  1.2097,  1.8297,  0.1822]])
Shape mới:  torch.Size([2, 6])
Số phần tử sau reshape(2, 6) : 12


In [6]:
# Bài 6
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

# Yêu cầu 1
print("\na * b:\n")
print(a * b)
print('Shape của a * b: ', (a * b).shape)

# Yêu cầu 2
print('\nShape của a @ b.T: ', (a @ b.T).shape)

a:
tensor([[ 0.2987, -1.0613, -0.2735],
        [ 0.2121, -1.1676, -0.9495]])
b:
tensor([[ 1.1564,  0.7623, -2.2178],
        [-0.4634,  0.5521, -1.4445]])

a + b:
tensor([[ 1.4551, -0.2990, -2.4913],
        [-0.2513, -0.6155, -2.3940]])

a / b:
tensor([[ 0.2583, -1.3922,  0.1233],
        [-0.4576, -2.1147,  0.6573]])

a^2:
tensor([[0.0892, 1.1263, 0.0748],
        [0.0450, 1.3634, 0.9016]])

Matrix multiplication:
tensor([[ 0.1430, -0.3293],
        [ 1.4610,  0.6286]])

a * b:

tensor([[ 0.3454, -0.8090,  0.6066],
        [-0.0983, -0.6447,  1.3716]])
Shape của a * b:  torch.Size([2, 3])

Shape của a @ b.T:  torch.Size([2, 2])


In [7]:
# Bài 7
import torch
a = torch.randn(3, 4)
print(a)

print("\nMean:")
print(torch.mean(a, dim=0))

print("\nStandard deviation:")
print(torch.std(a, dim=0))

print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

# Yêu cầu
print('\n Thay dim=0 bằng dim=1:')

print("\nMean:")
print(torch.mean(a, dim=1))

print("\nStandard deviation:")
print(torch.std(a, dim=1))

print("\nCumulative sum:")
print(torch.cumsum(a, dim=1))

tensor([[ 0.4959,  0.2272, -2.4379, -0.3636],
        [ 0.6931,  1.0716,  0.5977, -0.2119],
        [-0.7096,  0.6493,  0.1617, -0.2121]])

Mean:
tensor([ 0.1598,  0.6494, -0.5595, -0.2626])

Standard deviation:
tensor([0.7593, 0.4222, 1.6413, 0.0875])

Cumulative sum:
tensor([[ 0.4959,  0.2272, -2.4379, -0.3636],
        [ 1.1890,  1.2988, -1.8403, -0.5756],
        [ 0.4794,  1.9481, -1.6786, -0.7877]])

 Thay dim=0 bằng dim=1:

Mean:
tensor([-0.5196,  0.5376, -0.0277])

Standard deviation:
tensor([1.3283, 0.5400, 0.5754])

Cumulative sum:
tensor([[ 0.4959,  0.7231, -1.7148, -2.0785],
        [ 0.6931,  1.7646,  2.3623,  2.1504],
        [-0.7096, -0.0603,  0.1014, -0.1107]])


In [8]:
# Bài 8
import torch

x = torch.tensor(
    3.6,
    requires_grad=True
)

y = x * x

y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

# Yêu cầu 1
manual_grad_1 = 2 * 3.6
print("\nĐạo hàm thủ công (2*x tại x=3.6):", manual_grad_1)
print("Khớp kết quả:", torch.isclose(x.grad, torch.tensor(manual_grad_1)).item())

# Yêu cầu 2
x.grad.zero_()

y_new = 3 * x**2 + 2 * x + 1

y_new.backward()

print("\nx =", x)
print("y mới =", y_new)
print("x.grad mới =", x.grad)

manual_grad_2 = 6 * 3.6 + 2
print("Đạo hàm thủ công (6*x + 2 tại x=3.6):", manual_grad_2)
print("Khớp kết quả:", torch.isclose(x.grad, torch.tensor(manual_grad_2)).item())

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)

Đạo hàm thủ công (2*x tại x=3.6): 7.2
Khớp kết quả: True

x = tensor(3.6000, requires_grad=True)
y mới = tensor(47.0800, grad_fn=<AddBackward0>)
x.grad mới = tensor(23.6000)
Đạo hàm thủ công (6*x + 2 tại x=3.6): 23.6
Khớp kết quả: True


In [9]:
# Bài 9
import numpy as np
import torch

polynomial = np.poly1d([1, 2, 3])
N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("Learned coefficients:")
print(w)

# Yêu cầu
true_w = torch.tensor([[1.0], [2.0], [3.0]])
print("\nSo sánh sai số với [1, 2, 3]:")
print("Absolute Difference:\n", torch.abs(w - true_w))

Initial coefficients:
tensor([[ 0.7771],
        [ 0.1401],
        [-1.9716]], requires_grad=True)
Learned coefficients:
tensor([[1.0041],
        [1.9931],
        [2.7203]], requires_grad=True)

So sánh sai số với [1, 2, 3]:
Absolute Difference:
 tensor([[0.0041],
        [0.0069],
        [0.2797]], grad_fn=<AbsBackward0>)


In [10]:
# Bài 10
import random
import torch

A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()
    
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

# Yêu cầu
val_A, val_B, val_C, val_D = A.item(), B.item(), C.item(), D.item()

print(f"1. A + B = {val_A + val_B:.4f}")
print(f"2. C - D = {val_C - val_D:.4f}")
print(f"3. A + C = {val_A + val_C:.4f}")
print(f"4. B - D = {val_B - val_D:.4f}")
print(f"Tổng sai số bình phương (sqerr): {sqerr.item():.8f}")

A = tensor(4.2434, requires_grad=True)
B = tensor(4.7565, requires_grad=True)
C = tensor(3.7565, requires_grad=True)
D = tensor(2.7565, requires_grad=True)
1. A + B = 8.9999
2. C - D = 1.0000
3. A + C = 8.0000
4. B - D = 2.0000
Tổng sai số bình phương (sqerr): 0.00000000


In [11]:
# Bài 11
import numpy as np
import torch

# Yêu cầu 1
print('YÊU CẦU 1:')

X = torch.arange(24, dtype=torch.float32)

X_4x6 = X.reshape(4, 6)
X_2x12 = X.reshape(2, 12)
X_2x3x4 = X.reshape(2, 3, 4)

print("X shape gốc  :", X.shape)
print("Reshape 4x6  :\n", X_4x6)
print("Reshape 2x12 :\n", X_2x12)
print("Reshape 2x3x4:\n", X_2x3x4)

# Yêu cầu 2
print('\nYÊU CẦU 2:')

A = torch.randn(3, 4)
B = torch.randn(3, 4) + 2.0

print("A + B :\n", A + B)
print("A * B :\n", A * B)
print("A / B :\n", A / B)

print("A Mean theo cột (dim=0) :\n", torch.mean(A, dim=0))
print("A Std theo cột (dim=0)  :\n", torch.std(A, dim=0))
print("B Mean theo cột (dim=0) :\n", torch.mean(B, dim=0))
print("B Std theo cột (dim=0)  :\n", torch.std(B, dim=0))

# Yêu cầu 3
print("\nYÊU CẦU 3")
x = torch.tensor(2.0, requires_grad=True)
y = 2 * x**2 + 5 * x + 3

y.backward()

print("x =", x)
print("y =", y)
print("x.grad (Autograd) =", x.grad)

manual_grad = 4 * 2.0 + 5
print("Đạo hàm thủ công (4*2 + 5) =", manual_grad)

# Yêu cầu 4
print("\nYÊU CẦU 4")

polynomial = np.poly1d([2, -3, 5])
N = 20

X_np = np.random.randn(N, 1) * 5
Y_np = polynomial(X_np)

XX = np.hstack([X_np * X_np, X_np, np.ones_like(X_np)])

w = torch.randn(3, 1, requires_grad=True)
x_tensor = torch.tensor(XX, dtype=torch.float32)
y_tensor = torch.tensor(Y_np, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x_tensor @ w
    mse = torch.mean(torch.square(y_tensor - y_pred))
    mse.backward()
    optimizer.step()

print("Learned coefficients (Các hệ số tìm được):")
print(w)

YÊU CẦU 1:
X shape gốc  : torch.Size([24])
Reshape 4x6  :
 tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.],
        [12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]])
Reshape 2x12 :
 tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
        [12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.]])
Reshape 2x3x4:
 tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

YÊU CẦU 2:
A + B :
 tensor([[2.2832, 2.0511, 3.6764, 2.3527],
        [1.3826, 4.1868, 3.4356, 3.7576],
        [3.1339, 3.2718, 4.6434, 2.7924]])
A * B :
 tensor([[-0.0756, -2.2199,  2.9274,  1.0178],
        [-1.1882,  1.1876,  1.5138, -0.7845],
        [ 2.3303,  0.0301,  3.6148, -0.0904]])
A / B :
 tensor([[-0.0141, -0.2763,  0.4646,  0.3208],
        [-0.3024,  0.0789,  0.1780, -0.0501],
        [ 0.6318,  0